### ISSUE TITLE
Fix deployment of README.md to DockerHub

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-docker#77]
### Summary

Right now the deployment does not work, and the README is dated. We need to fix the GitHub action and, ideally, detach it to CD 

Right now we use https://github.com/peter-evans/dockerhub-description, most likely an update to v3 is needed

```
      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: wiremockbot
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: wiremock/wiremock
          short-description: Official images for the WireMock standalone server
          readme-filepath: ./readme.md
```

### References

- https://hub.docker.com/r/wiremock/wiremock
- https://github.com/wiremock/wiremock-docker/blob/main/.github/workflows/release.yml
